language: minimal
services: docker
before_install:
  - sudo apt-get install moreutils
  - set -o pipefail
before_script:
  - ${TRAVIS_BUILD_DIR}/pipeline/shared/sync_repo.sh
addons:
  coverity_scan:
    project:
      name: "duplicati/duplicati"
      description: "Duplicati Build submitted via Travis CI"
    notification_email: hendrik@natural-transformations.com
    build_command_prepend: "msbuild /t:Clean"
    build_command: "msbuild /t:Rebuild"
    branch_pattern: coverity_scan
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "ijaQDcVcMo/utuP514FiDZVGR5LJbATWmYDmgRIIaI0YG2Rk6uuJp9XXDXr8sx66JWttPGgs7Htqfy50VKHdr7nsfyCQCRNGmqF+OJeUgAQMj5spxn9A7PZY9+GVhnXoJ06wvYjCv5MPeLBMDK/KpIM5Ny5IG+TKzQy4U7Dyg0riMUT61aqzxSjTGfHZPmaqBICJTzsRmeGHglemFUz/1B4NAN+IeAtXoH9YIfA2LjJfYmMLckPgFQLKN/tQRaGPWXh77y0qVgA++K8UVu5W3yGo3JXBPDdabGgKs9BPlfN5/Ixnkcy6ekAubDA/Aspur9x7/szj4/AnGMY6frNB33nQcnJQZ/51GYKr6CXCmjoJQuWc8ZKdEMqDn3w/kyEzvluSjAsJNRVboeWPE4VfpAeUBsjQ+TuEQi8WXhN8VJgZV7yCkVlZTVbhtOxMPsBiFb74lpWC2iQuWLJv9ED6vyXZVzZhNtfjXNXNZzIwYxbcd7I0ZQ8fmDstFnvBJveJby2ZRpECXTbc03eIUq1SAaVJJY2r47RD1PwVqM3xvUTljIqtKdyIz915mEOjqG1BnCDaiGHYJ4byuDDeIUZO9X70s60Gh4hupZA2Ruup0v7SfYgkto6aNcStd0NYd716Vd7hqXNTp6nu01L5YYJDY4h5sHyBXVXbxCKlUb01kUw="
    - USAGEREPORTER_Duplicati_LEVEL=none
    - AUTOUPDATER_Duplicati_SKIP_UPDATE=1
    - BUILD_DIR=${TRAVIS_BUILD_DIR}/.build
    - TEST_DIR=${TRAVIS_BUILD_DIR}/.test
    - ARCHIVE_DIR=${TRAVIS_BUILD_DIR}/.zip
    - PACKAGES_DIR=${TRAVIS_BUILD_DIR}/.packages
    - SIGN_DIR=${TRAVIS_BUILD_DIR}/.sign
    - UPLOAD_DIR=${TRAVIS_BUILD_DIR}/.upload
    - AUTO_UPDATE_KEY_FILE="/keys/autoupdate.key.aes"
    - GPG_CREDENTIALS_FILE="/keys/gpg_id_passphrase.key.aes"
    - GPG_KEY_FILE="/keys/gpg.key.aes"
    - DOCKER_USER="duplicatipipeline"
    - DOCKER_REPO="duplicatipipeline/duplicati"
    - ROOT_DIR="$TRAVIS_BUILD_DIR"

# matrix expansion within jobs would be good:
# https://github.com/travis-ci/travis-ci/issues/8295

# There is one cache per branch, so concurrent builds on different branches possible!
# DO NOT SET ENVIRONMENT VARIABLES WITHIN JOBS, OR CACHES WILL NOT BE SHARED AMONGST JOBS!


jobs:
  include:
    - stage: build
      cache:
        directories:
          - $BUILD_DIR
      script:
        - ${ROOT_DIR}/pipeline/jobs/build_job.sh


    - stage: unit tests
      cache:
        directories:
          - $HOME/download/
          - $BUILD_DIR
      script:
        - ${ROOT_DIR}/pipeline/jobs/unittest1_job.sh
    - stage: unit tests
      cache:
        directories:
          - $HOME/download/
          - $BUILD_DIR
      script:
        - ${ROOT_DIR}/pipeline/jobs/unittest2_job.sh
    - stage: unit tests
      cache:
        directories:
          - $HOME/download/
          - $BUILD_DIR
      script:
        - ${ROOT_DIR}/pipeline/jobs/unittest3_job.sh
    - stage: unit tests
      cache:
        directories:
          - $HOME/download/
          - $BUILD_DIR
      script:
        - ${ROOT_DIR}/pipeline/jobs/unittest4_job.sh
    - stage: unit tests
      cache:
        directories:
          - $HOME/download/
          - $BUILD_DIR
      script:
        - ${ROOT_DIR}/pipeline/jobs/unittest5_job.sh

    - stage: integration tests
      cache:
        directories:
          - $HOME/download/
          - $BUILD_DIR
      script:
        - ${ROOT_DIR}/pipeline/jobs/selenium_job.sh
      addons:
        sauce_connect:
          username: $SAUCE_USERNAME
          access_key: $SAUCE_ACCESS_KEY

    - stage: create main package
      cache:
        directories:
          - ${ARCHIVE_DIR}
          - $BUILD_DIR
        timeout: 1800
      script:
        - ${ROOT_DIR}/pipeline/jobs/package_job.sh

    - stage: create platform packages
      cache:
        directories:
          - $BUILD_DIR
          - ${ARCHIVE_DIR}
          - ${PACKAGES_DIR}
        timeout: 1800
      script:
        - ${ROOT_DIR}/pipeline/jobs/packages_job.sh

    - stage: sign binaries
      cache:
        directories:
          - $BUILD_DIR
          - ${PACKAGES_DIR}
          - ${SIGN_DIR}
        timeout: 1800
      script:
        - ${ROOT_DIR}/pipeline/jobs/sign_job.sh

    - stage: upload to docker and aws
      cache:
        directories:
          - $BUILD_DIR
          - ${PACKAGES_DIR}
          - ${SIGN_DIR}
        timeout: 1800
      script:
        - ${ROOT_DIR}/pipeline/jobs/upload_job.sh

